# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 13:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import resmin.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCandidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Olu\u015fturulma Zaman\u0131')),
                ('email', models.EmailField(max_length=254, verbose_name='eposta')),
                ('key', models.CharField(blank=True, max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Sahip')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=255)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('use_limit', models.PositiveIntegerField(default=20)),
                ('is_usable', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('registered_users', models.ManyToManyField(blank=True, related_name='registed_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['is_usable'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(blank=True, max_length=255, null=True, verbose_name='biografi')),
                ('website', models.URLField(blank=True, null=True, verbose_name='internet sitesi')),
                ('facebook', models.SlugField(blank=True, null=True, verbose_name='facebook username')),
                ('instagram', models.SlugField(blank=True, null=True, verbose_name='instagram username')),
                ('twitter', models.SlugField(blank=True, null=True, verbose_name='twitter username')),
                ('github', models.SlugField(blank=True, null=True, verbose_name='github username')),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('follower_count', models.PositiveIntegerField(default=0)),
                ('following_count', models.PositiveIntegerField(default=0)),
                ('story_count', models.PositiveIntegerField(default=0)),
                ('location', models.CharField(blank=True, max_length=64, null=True, verbose_name='konum')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=resmin.utils.filename_for_avatar)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
