# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 13:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_anonymouse', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, b'Pending'), (1, b'Answered'), (2, b'Rejected')], default=0)),
                ('answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='story.Story')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=512, verbose_name='Soru')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_sponsored', models.BooleanField(default=False)),
                ('answer_count', models.PositiveIntegerField(default=0)),
                ('follower_count', models.PositiveIntegerField(default=0)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, b'Published '), (2, b'Deleted by Admins')], default=0)),
                ('cover_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cover_answer', to='story.Story')),
                ('latest_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='latest_answer', to='story.Story')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('redirected_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='question.QuestionMeta')),
            ],
            options={
                'ordering': ['-is_featured', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionMetaComplaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_type', models.PositiveIntegerField(choices=[(0, 'Ayn\u0131s\u0131 Var'), (1, 'Anlams\u0131z'), (2, 'Nefret S\xf6ylemi'), (3, 'Hakaret')], verbose_name='\u015eikayet tipi')),
                ('status', models.PositiveIntegerField(choices=[(0, 'Bekliyor'), (1, '\xc7\xf6z\xfcld\xfc'), (2, 'Reddedildi')], default=0)),
                ('description', models.TextField(blank=True, null=True, verbose_name='A\xe7\u0131klama')),
                ('complainers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('question_meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.QuestionMeta')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='meta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.QuestionMeta'),
        ),
        migrations.AddField(
            model_name='question',
            name='questionee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='questioner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questioner', to=settings.AUTH_USER_MODEL),
        ),
    ]
