# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 13:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import resmin.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('md5sum', models.CharField(blank=True, max_length=36)),
                ('image', models.ImageField(upload_to=resmin.utils.filename_for_image)),
                ('taken_at', models.DateTimeField(blank=True, null=True)),
                ('mime_type', models.CharField(max_length=64)),
                ('is_playble', models.BooleanField()),
            ],
            options={
                'verbose_name': 'G\xf6rsel',
                'verbose_name_plural': 'G\xf6rseller',
            },
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(null=True)),
                ('title', models.CharField(blank=True, max_length=144, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('cPk', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cTp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'ordering': ['story', 'order'],
                'verbose_name': 'Slot',
                'verbose_name_plural': 'Slotlar',
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Olu\u015fturulma Zaman\u0131')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ba\u015fl\u0131k')),
                ('cover_img', jsonfield.fields.JSONField(blank=True, null=True, verbose_name='Kapak G\xf6rseli')),
                ('description', models.TextField(blank=True, null=True, verbose_name='A\xe7\u0131klama')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Vizyonda')),
                ('is_nsfw', models.BooleanField(default=False, verbose_name='AYIP')),
                ('is_anonymouse', models.BooleanField(default=False, verbose_name='Ad\u0131m\u0131 Gizle')),
                ('is_playble', models.BooleanField(default=False)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('slot_count', models.PositiveIntegerField(blank=True, null=True)),
                ('comment_count', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Taslak'), (1, 'Yay\u0131nda'), (2, 'Sahibi Taraf\u0131ndan Silinmi\u015f'), (3, 'Adminler Taraf\u0131ndan Silinmi\u015f')], default=0, verbose_name='Durum')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Updated at')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Sahip')),
            ],
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'Hikaye',
                'verbose_name_plural': 'Hikayeler',
            },
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_id', models.CharField(default=resmin.utils.generate_upload_id, editable=False, max_length=32, unique=True)),
                ('file', models.FileField(max_length=255, upload_to=resmin.utils.filename_for_upload)),
                ('mime_type', models.CharField(max_length=64)),
                ('offset', models.PositiveIntegerField(default=0)),
                ('size', models.PositiveIntegerField()),
                ('md5sum', models.CharField(blank=True, max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.CharField(blank=True, choices=[(b'image', b'Image'), (b'video', b'Video')], max_length=64)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Y\xfckleniyor'), (2, 'Tamamland\u0131'), (3, 'Bitirilemedi')], default=1)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Sahip')),
            ],
            options={
                'verbose_name': 'Y\xfckleme',
                'verbose_name_plural': 'Y\xfcklemeler',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('md5sum', models.CharField(blank=True, max_length=36)),
                ('video', models.FileField(upload_to=resmin.utils.filename_for_video)),
                ('frame', models.ImageField(blank=True, upload_to=resmin.utils.filename_for_video_frame)),
                ('taken_at', models.DateTimeField(blank=True, null=True)),
                ('mime_type', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videolar',
            },
        ),
        migrations.AddField(
            model_name='slot',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='story.Story'),
        ),
    ]
