# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
        ('question', '0001_initial'),
    ]
    operations = [
        migrations.AddField(
            model_name='story',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.deletion.CASCADE, to='question.Question'),
        ),
        migrations.AddField(
            model_name='story',
            name='question_meta',
            field=models.ForeignKey(on_delete=models.deletion.CASCADE, to='question.QuestionMeta'),
        ),
    ]
